name: infixedu
description: A new Flutter project.

publish_to: 'none'

version: 2.5.0+42

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  equatable: ^2.0.5
  file_picker: ^5.2.7
  file_utils: ^1.0.1
  flutter_bloc: ^8.1.2
  flutter_calendar_carousel: ^2.4.3
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_cupertino_localizations: ^1.0.1
  flutter_local_notifications: ^9.7.0
  flutter_webview_plugin:
    git: https://github.com/jiankian/flutter_webview_plugin
  fluttertoast: ^8.2.1
  http: ^0.13.5
  open_filex: ^4.3.2
  path_provider: ^2.0.14
  rxdart: ^0.27.7
  scoped_model: ^2.0.0
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.2
  url_launcher: ^6.1.10
  intl: 0.18.0
  flutter_overlay_loader: ^2.0.0
  flutter_cache_manager: ^3.3.0
  timeago: ^3.0.2
  flutter_slidable: ^0.6.0-nullsafety.0
  font_awesome_flutter: ^10.4.0
  pdf_flutter:
    git: https://github.com/erluxman/pdf_flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_inappwebview: ^5.7.2+3
  extended_image: ^7.0.2
  firebase_core: ^2.4.0
  firebase_messaging: ^14.5.0
  flutter_dropdown_alert: ^1.0.1
  edge_alert: ^0.0.1
  flutter_screenutil: ^5.7.0
  flutter_widget_from_html: ^0.8.5
  permission_handler: ^10.2.0
  http_auth: ^1.0.1
  flutter_paystack:
    git:
      url: https://github.com/pravinpawar5788/flutter_paystack.git
      ref: master
  flutter_credit_card: ^3.0.0
  carousel_slider: ^4.0.0
  persistent_bottom_nav_bar: ^4.0.2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  get: ^4.6.5
  google_fonts: ^4.0.3
  badges: ^2.0.1
  stripe_sdk: ^5.0.0-nullsafety.1
  flutter_portal: ^1.1.3
  file: ^7.0.0
  loading_more_list: ^5.0.3
  let_log: ^1.1.4
  emoji_picker_flutter: ^1.0.8
  flutter_easyloading: ^3.0.5
  photo_view: ^0.14.0
  better_player: ^0.0.83
  flutter_staggered_animations: ^1.1.1
  razorpay_flutter: ^1.2.7
  reorderables:
    git: https://github.com/emran92/reorderables
  pusher_channels_flutter: ^2.1.2
  khalti: ^0.0.1
  html_editor_enhanced: ^2.5.1
  eko_jitsi:
    git: https://github.com/emran92/eko_jitsi
  flutter_html: ^3.0.0-alpha.5

dependency_overrides:
  intl: 0.18.0
  let_log:
    git:
      url: https://github.com/pravinpawar5788/let_log.git
      ref: master
  themify_flutter:
    git:
      url: https://github.com/pravinpawar5788/themify_flutter.git
      ref: patch-1
  edge_alert:
    git:
      url: https://github.com/pravinpawar5788/EdgeAlert.git
      ref: master
  flutter_cupertino_localizations:
    git:
      url: https://github.com/pravinpawar5788/flutter_cupertino_localizations.git
      ref: master
  flutter_calendar_carousel:
    git:
      url: https://github.com/pravinpawar5788/flutter_calendar_carousel.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.9
  import_sorter: ^4.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_icon.jpg"

flutter_native_splash:
  image: assets/config/splash_logo.png
  fullscreen: true
  color: "FFFFFF"

flutter:
  uses-material-design: true
  assets:
   - assets/config/
   - assets/images/
   - assets/locale/

fonts:
  - family: popins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500
